apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  labels:
    app: mysql-database
spec:
  containers:
  - name: mysql-db-container
    image: 831394104903.dkr.ecr.us-east-1.amazonaws.com/assignment1-database:v0.1
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mitul#9090
    ports:
    - containerPort: 3306