apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: web-app-container
          image: 831394104903.dkr.ecr.us-east-1.amazonaws.com/assignment1-webapp:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: 10.244.0.5
            - name: DBPORT
              value: "3306"
            - name: DBPWD
              value: "mitul#9090"
