apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app.kubernetes.io/name: mysql-database
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: mysql-database
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
